version: '3'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
